"""Added api keys

Revision ID: 3e8b1173b999
Revises: df0a20fbb38b
Create Date: 2026-03-18 18:31:25.490308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e8b1173b999'
down_revision: Union[str, Sequence[str], None] = 'df0a20fbb38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.drop_table('ping_logs_2026_03_15')
    op.drop_table('ping_logs_2026_03_16')
    op.drop_table('ping_logs_2026_03_17')
    op.drop_table('ping_logs_2026_03_18')
    op.drop_table('ping_logs_2026_03_19')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping_logs_2026_03_19',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_up', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('ping_logs_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('ping_logs_2026_03_19_pkey'))
    )
    op.create_table('ping_logs_2026_03_18',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_up', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('ping_logs_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('ping_logs_2026_03_18_pkey'))
    )
    op.create_table('ping_logs_2026_03_17',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_up', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('ping_logs_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('ping_logs_2026_03_17_pkey'))
    )
    op.create_table('ping_logs_2026_03_16',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_up', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('ping_logs_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('ping_logs_2026_03_16_pkey'))
    )
    op.create_table('ping_logs_2026_03_15',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_up', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('ping_logs_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('ping_logs_2026_03_15_pkey'))
    )
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
