"""monitor_alerts to monitor_channels

Revision ID: a923e623adbc
Revises: 4447bec48223
Create Date: 2026-03-13 11:34:50.401248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a923e623adbc'
down_revision: Union[str, Sequence[str], None] = '4447bec48223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_channels',
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('alert_channel_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alert_channel_id'], ['alert_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitor_id', 'alert_channel_id')
    )
    op.drop_table('monitor_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_alerts',
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alert_channel_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_channel_id'], ['alert_channels.id'], name=op.f('monitor_alerts_alert_channel_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('monitor_alerts_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitor_id', 'alert_channel_id', name=op.f('monitor_alerts_pkey'))
    )
    op.drop_table('monitor_channels')
    # ### end Alembic commands ###
