"""change interval_minutes to interval_seconds

Revision ID: c6ac3fbeeaf7
Revises: e8d43added40
Create Date: 2026-03-12 00:32:34.105602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ac3fbeeaf7'
down_revision: Union[str, Sequence[str], None] = 'e8d43added40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('interval_seconds', sa.Integer(), nullable=False))
    op.drop_column('monitors', 'interval_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('interval_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('monitors', 'interval_seconds')
    # ### end Alembic commands ###
