"""organization_users enum update

Revision ID: df0a20fbb38b
Revises: a923e623adbc
Create Date: 2026-03-15 21:07:31.051721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df0a20fbb38b'
down_revision: Union[str, Sequence[str], None] = 'a923e623adbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ping_logs_2026_03_14')
    op.drop_table('ping_logs_2026_03_13')
    op.drop_table('ping_logs_2026_03_15')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping_logs_2026_03_15',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_up', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('ping_logs_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('ping_logs_2026_03_15_pkey'))
    )
    op.create_table('ping_logs_2026_03_13',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_up', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('ping_logs_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('ping_logs_2026_03_13_pkey'))
    )
    op.create_table('ping_logs_2026_03_14',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_up', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('ping_logs_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name=op.f('ping_logs_2026_03_14_pkey'))
    )
    # ### end Alembic commands ###
